[package]
name = "api"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[[bin]]
name = "mailquill"
path = "src/main.rs"

[dependencies]
mailquill-core = { path = "../core" }
db = { path = "../db" }
mail-sync = { path = "../mail-sync" }
phishing = { path = "../phishing" }
smtp = { path = "../smtp" }
contact-sync = { path = "../contact-sync" }
calendar-sync = { path = "../calendar-sync" }
axum = { version = "0.8", features = ["macros"] }
rust-embed = { version = "8", features = ["axum-ex"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace", "set-header"] }
jsonwebtoken = "9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
mime_guess = "2"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "macros", "migrate", "chrono", "uuid"] }
argon2 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
oauth2 = "4"
rand = "0.8"
hex = "0.4"
strsim = "0.11"
thiserror = "2"
async-trait = "0.1"
urlencoding = "2"
figment = { version = "0.10", features = ["toml", "yaml", "env"] }
web-push = "0.11"
p256 = "0.13"
clap = { version = "4", features = ["derive"] }
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
tokio-native-tls = "0.3"
native-tls = "0.2"
base64 = "0.22"
hickory-resolver = "0.24"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
quick-xml = "0.37"
sha2 = "0.10"
