[workspace]
members = [
    "backend/core",
    "backend/api",
    "backend/db",
    "backend/mail-sync",
    "backend/phishing",
    "backend/smtp",
    "backend/calendar-sync",
    "backend/contact-sync",
    "backend/bench",
    "xtask",
]
resolver = "2"

default-members = ["backend/api"]

[profile.release]
strip = true
lto = true
codegen-units = 1
