[package]
name = "calendar-sync"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
reqwest = { workspace = true, features = ["json"] }
quick-xml = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
urlencoding = { workspace = true }
