[package]
name = "bench"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
db = { workspace = true }
sqlx = { workspace = true, features = ["macros"] }
tokio = { workspace = true }
rand = { workspace = true }
anyhow = "1"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "mail_list"
harness = false
